curl: Autospec creation for update from version 7.70.0 to version 7.71.1
Adnan Khan (1):
      HTTP3.md: clarify cargo build directory

Alessandro Ghedini (1):
      quiche: update SSLKEYLOGFILE support

Baruch Siach (1):
      mbedtls: fix build with disabled proxy support

Cherish98 (1):
      socks: fix expected length of SOCKS5 reply

Dan Fandrich (2):
      tests: Stop referring to server ports when they're not used
      test75: Remove precheck test

Daniel Stenberg (180):
      RELEASE-NOTES: synced
      schannel: source code reindent
      tests: pick a random port number for SSH
      tests: tests: run stunnel for HTTPS and FTPS on dynamic ports
      conncache: various concept cleanups
      cirrus: disable SFTP and SCP tests
      examples: remove asiohiper.cpp
      tests: make test 1248 + 1249 use %NOLISTENPORT
      runtests: make the logmsg from the ssh server only show in verbose
      libssh2: set the expected total size in SCP upload init
      RELEASE-NOTES: synced
      asyn-*: remove support for never-used NULL entry pointers
      runtests: remove sleep calls
      dynbuf: introduce internal generic dynamic buffer functions
      http_proxy: ported to use dynbuf instead of a static size buffer
      connect: add two asserts to clue code analyzers in a little
      connect: make happy eyeballs work for QUIC (again)
      ngtcp2: convert to dynbuf
      urldata.h: remove #define HEADERSIZE, not used anymore
      quiche: enable qlog output
      travis: add "qlog" as feature in the quiche build
      libssh2: convert over to use dynbuf
      runtests: set +x mode again
      http2: simplify and clean up trailer handling
      RELEASE-NOTES: synced
      runtests: show elapsed test time with higher precision (ms)
      ntlm_sspi: fix bad use of CURLE_NOT_BUILT_IN
      ngtcp2: introduce qlog support
      docs/HTTP3: add qlog to the quiche build instruction
      THANKS-filter: Peter Wang
      urlapi: accept :: as a valid IPv6 address
      TODO: native IDN support on macOS
      RELEASE-NOTES: synced
      checksrc: close the .checksrc file handle when done reading
      tool_operate: only set CURLOPT_SSL_OPTIONS if SSL support is present
      ROADMAP: remove old entries
      KNOWN_BUGS: Build with staticly built dependency
      write-out.d: added "response_code"
      url: sort the protocol schemes in rough popularity order
      runtests: remove ftp2 support, not used
      FILEFORMAT: moved up the variables section and further polished
      list-only.d: this option existed already in 4.0
      url: reject too long input when parsing credentials
      RELEASE-NOTES: synced
      configure: the wolfssh backend does not provide SCP
      tool: shorten 3 --help descriptions
      cert-type.d: mention the available types in the desc
      sasl-authzid.d: add Arg: and shorten the desc
      tls13-ciphers.d: shorten the Arg
      OpenSSL: have CURLOPT_CRLFILE imply CURLSSLOPT_NO_PARTIALCHAIN
      docs: unify protocol lists
      docs/options-in-versions: which version added each cmdline option
      checksrc: enhance the ASTERISKSPACE and update code accordingly
      mailmap: James Fuller
      tests: add https-proxy support to the test suite
      url: make the updated credentials URL-encoded in the URL
      ftp: shut down the secondary connection properly when SSL is used
      sws: as last resort, get test number from server cmd file
      test1631: verify FTP download through HTTPS-proxy
      test1632: verify FTP through HTTPS-proxy with connection re-use
      ftp: make domore_getsock() return the secondary socket properly
      travis: remove the .checksrc fiddling
      source cleanup: remove all custom typedef structs
      KNOWN_BUGS: OS400 port requires deprecated IBM library
      KNOWN_BUGS: wolfssh: publickey auth doesn't work
      dynbuf: return NULL when there's no buffer length
      RELEASE-NOTES: synced
      TODO: forbid TLS post-handshake auth and do TLS record padding
      ftp: mark return-ignoring calls to Curl_GetFTPResponse with (void)
      hostip: make Curl_printable_address not return anything
      sendf: make failf() use the mvsnprintf() return code
      sha256: move assign to the declaration line
      tool_paramhlp: fixup C89 mistake
      TODO: Ratelimit or wait between serial requests
      TODO: --dry-run
      typecheck-gcc.h: fix the OFF_T check
      tests/server/util.h: add extern to silence compiler warning
      typecheck-gcc.h: CURLINFO_PRIVATE does not need a 'char *'
      Revert "sendf: make failf() use the mvsnprintf() return code"
      curl: remove -J "informational" written on stdout
      copyright: updated year ranges out of sync
      RELEASE-NOTES: synced
      RELEASE-NOTES: synced
      altsvc: fix parser for lines ending with CRLF
      url: accept "any length" credentials for proxy auth
      cleanup: use a single space after equals sign in assignments
      quiche: clean up memory properly when failing to connect
      ngtcp2: cleanup memory when failing to connect
      hostip: on macOS avoid DoH when given a numerical IP address
      urldata: connect related booleans live in struct ConnectBits
      FILEFORMAT: add more features that tests can depend on
      urldata: fix comments: Curl_done() is called multi_done() now
      configure: repair the check if argv can be written to
      mk-lib1521: generate code for testing BLOB options as well
      libssh2: improved error output for wrong quote syntax
      server/sws: fix asan warning on use of uninitialized variable
      Revert "buildconf: use find -execdir"
      RELEASE-NOTES: synced
      timeouts: change millisecond timeouts to timediff_t from time_t
      url: alloc the download buffer at transfer start
      build: disable more code/data when built without proxy support
      conncache: download buffer needs +1 size for trailing zero
      transfer: remove k->str NULL check
      test970: make it require proxy support
      hostip: fix the memory-leak introduced in 67d2802
      urldata: let the HTTP method be in the set.* struct
      RELEASE-NOTES: synced
      altsvc: fix 'dsthost' may be used uninitialized in this function
      KNOWN_BUGS: RTSP authentication breaks without redirect support
      configure: only strip first -L from LDFLAGS
      mailmap: Don J Olmstead
      CURLINFO_ACTIVESOCKET.3: clarify the description
      trailers: switch h1-trailer logic to use dynbuf
      user-agent.d: spell out what happens given a blank argument
      RELEASE-NOTES: synced
      server/util: fix logmsg format using curl_off_t argument
      libssh2: keep sftp errors as 'unsigned long'
      tool_cfgable: free login_options at exit
      ngtcp2: update with recent API changes
      tests: add two simple tests for --login-options
      Curl_addrinfo: use one malloc instead of three
      socks: detect connection close during handshake
      wording: avoid blacklist/whitelist stereotypes
      RELEASE-NOTES: synced
      buildconf: remove -print from the find command that removes files
      share: don't set the share flag it something fails
      mailmap: Nicolas Sterchele
      TODO: retry on the redirected-to URL
      HELP-US: add a section for "smaller tasks"
      ABI.md: rename to .md and polish the markdown
      version.d: expanded and alpha-sorted
      altsvc: remove the num field from the altsvc struct
      CODE_REVIEW.md: how to do code reviews in curl
      http: move header storage to Curl_easy from connectdata
      configure: for wolfSSL, check for the DES func needed for NTLM
      RELEASE-NOTES: synced
      manpage: add three missing environment variables
      select: remove the unused ELAPSED_MS() macro
      ngtcp2: fix happy eyeballs quic connect crash
      ngtcp2: never call fprintf() in lib code in release version
      connect: improve happy eyeballs handling
      FILEFORMAT: describe verify/stderr
      tool_getparam: repair the error message for unknown flag
      test1179: verify error message for non-existing cmdline option
      urlglob: treat literal IPv6 addresses with zone IDs as a host name
      altsvc: bump to h3-29
      tool_getparam: -i is not OK if -J is used
      test1460: verify that -Ji is not ok
      copyright: update mismatched copyright years
      url: make sure pushed streams get an allocated download buffer
      THANKS: curl 7.71.0 additions
      RELEASE-NOTES: curl 7.71.0 release
      curlver: start working on 7.71.1
      RELEASE-NOTES: synced
      sendf: improve the message on client write errors
      Curl_inet_ntop: always check the return code
      escape: zero length input should return a zero length output
      test543: extended to verify zero length input
      http2: set the correct URL in pushed transfers
      escape: make the URL decode able to reject only %00 bytes
      url: allow user + password to contain "control codes" for HTTP(S)
      tests: verify newline in username and password for HTTP
      gtihub: codeql-analysis.yml
      codeql-analysis.yml: fix the 'languages' setting
      test1539: do a HTTP 1.0 POST without a set size (fails)
      CURLOPT_READFUNCTION.3: provide the upload data size up front
      .dcignore: ignore tests and docs directories
      http: fix proxy auth with blank password
      terminology: call them null-terminated strings
      RELEASE-NOTES: synced
      vtls: compare cert blob when finding a connection to reuse
      examples/multithread.c: call curl_global_cleanup()
      ngtcp2: sync with current master
      cirrus-ci: disable FreeBSD 13 (again)
      TODO: return code to CURLMOPT_PUSHFUNCTION to fail connection
      TODO: Add flag to specify download directory
      Revert "multi: implement wait using winsock events"
      scripts/copyright.pl: skip .dcignore
      THANKS: add contributors to 7.71.1
      RELEASE-NOTES: curl 7.71.1

Denis Baručić (1):
      DYNBUF.md: fix a typo: trail => tail

Emil Engler (5):
      GnuTLS: Backend support for CURLINFO_SSL_VERIFYRESULT
      runtests: fix typo in the existence of disabled tests checker
      KNOWN_BUGS: Remove "curl --upload-file . hang if delay in STDIN"
      doc: add missing closing parenthesis in CURLINFO_SSL_VERIFYRESULT.3
      doc: Rename VERSIONS to VERSIONS.md as it already has Markdown syntax

Estanislau Augé-Pujadas (1):
      Revert "ssh: ignore timeouts during disconnect"

François Rigault (1):
      openssl: set FLAG_TRUSTED_FIRST unconditionally

Gilles Vollant (3):
      CURLOPT_SSL_OPTIONS: add *_NATIVE_CA to use Windows CA store (with openssl)
      setopt: support certificate options in memory with struct curl_blob
      setopt: add CURLOPT_PROXY_ISSUERCERT(_BLOB) for coherency

James Fuller (2):
      socks: remove unreachable breaks in socks.c and mime.c
      multi: add defensive check on data->multi->num_alive

James Le Cuirot (1):
      libcurl.pc: Merge Libs.private into Libs for static-only builds

Javier Blazquez (1):
      openssl: Fix compilation on Windows when ngtcp2 is enabled

Jay Satiro (11):
      select: fix overflow protection in Curl_socket_check
      asyn-thread: fix cppcheck warning
      tool: Add option --retry-all-errors to retry on any error
      retry-all-errors.d: Shorten the summary line
      curl.1: Quote globbed URLs
      projects: Add crypt32.lib to dependencies for all OpenSSL configs
      tool_getparam: fix memory leak in parse_args
      openssl: Fix CA fallback logic for OpenSSL 3.0 build
      tool_operate: Don't use Windows CA store as a fallback
      openssl: Don't ignore CA paths when using Windows CA store
      tool_cb_hdr: Fix etag warning output and return code

Kamil Dudka (2):
      tests: look for preprocessed tests in build directory
      test1177: look for curl.h in source directory

Major_Tom (1):
      vauth/cleartext: fix theoretical integer overflow

Maksim Stsepanenka (1):
      test1167: fixes in badsymbols.pl

Marc Hoersken (22):
      tests: add support for SSH server variant specific transfer paths
      tests/server/util.c: use raise instead of calling signal handler
      tests/server/util.c: fix thread handle not being closed
      tests/server/util.[ch]: add exit event to stop waiting on Windows
      sockfilt: make select_ws stop waiting on exit signal event
      test613.pl: make tests 613 and 614 work with OpenSSH for Windows
      appveyor: disable flaky test 1501 and ignore broken 1056
      appveyor: disable test 1139 instead of ignoring it
      TODO: update regarding missing Schannel features
      appveyor: update comments to be clear about toolchain
      tests/server/tftpd.c: fix include and enhance debug logging
      test1238: avoid tftpd being busy for tests shortly following
      appveyor: add non-debug plain autotools-based build
      tests/libtest: fix undefined reference to 'curlx_win32_fopen'
      unit1604.c: fix implicit conv from 'SANITIZEcode' to 'CURLcode'
      select: use timediff_t instead of time_t and int for timeout_ms
      select: add overflow checks for timeval conversions
      azure: use matrix strategy to avoid configuration redundancy
      select: always use Sleep in Curl_wait_ms on Win32
      CI/macos: fix 'is already installed' errors by using bundle
      .gitignore: add directory containing the stats repo
      timeouts: move ms timeouts to timediff_t from int and long

Marcel Raad (4):
      curl_multibyte: add to curlx
      tool: support UTF-16 command line on Windows
      curl_setup: support Unicode functions to open files on Windows
      KNOWN_BUGS: adapt 5.5 to recent changes

Martin V (1):
      test1560: avoid possibly negative association in wording

Michael Kaufmann (1):
      transfer: close connection after excess data has been read

Nicolas Sterchele (1):
      TODO: remove 19.3 section title

Peter Wang (1):
      *_sspi: fix bad uses of CURLE_NOT_BUILT_IN

Peter Wu (17):
      CMake: add HTTP/3 support (ngtcp2+nghttp3, quiche)
      CMake: add ENABLE_ALT_SVC option
      travis: Add ngtcp2 and quiche tests for CMake
      CMake: do not build test programs by default
      CMake: fix runtests.pl with CMake, add new test targets
      CMake: add libssh build support
      travis: whitespace-only changes for consistency
      travis: upgrade to bionic, clang-9, improve readability
      configure: fix pthread check with static boringssl
      travis: simplify quiche build instructions wrt boringssl
      ngtcp2: fix build with current ngtcp2 master implementing draft 28
      vtls: Extract and simplify key log file handling from OpenSSL
      wolfssl: add SSLKEYLOGFILE support
      ngtcp2: use common key log routine for better thread-safety
      CMake: rebuild Makefile.inc.cmake when Makefile.inc changes
      quiche: advertise draft 28 support
      CMake: ignore INTERFACE_LIBRARY targets for pkg-config file

Radoslav Georgiev (1):
      examples/http2-down/upload: add error checks

Rikard Falkeborn (1):
      libtest/cmake: Remove commented code

Ruurd Beerstra (1):
      ntlm: enable NTLM support with wolfSSL

Saleem Abdulrasool (1):
      vtls: repair the build with `CURL_DISABLE_PROXY`

Siva Sivaraman (3):
      sha256: fixed potentially uninitialized variable
      tool_operate: fixed potentially uninitialized variables
      tool_paramhlp: fixed potentially uninitialized strtol() variable

Valentyn Korniienko (1):
      multibyte: Fixed access-> waccess to file for Windows Plarform

Viktor Szakats (1):
      all: fix codespell errors

Vyron Tsingaras (1):
      http2: keep trying to send pending frames after req.upload_done

denzor (1):
      easy: fix dangling pointer on easy_perform fail

kotoriのねこ (1):
      examples/ephiperfifo: turn off interval when setting timerfd

rcombs (1):
      multi: implement wait using winsock events