curl: Autospec creation for update from version 7.68.0 to version 7.69.0
Alessandro Ghedini (1):
      quiche: update to draft-25

Anderson Toshiyuki Sasaki (1):
      libssh: improve known hosts handling

Aron Rotteveel (1):
      form.d: fix two minor typos

Cristian Greco (1):
      configure.ac: fix comments about --with-quiche

Dan Fandrich (1):
      cirrus: Add some missing semicolons

Daniel Stenberg (112):
      RELEASE-PROCEDURE.md: fix next release date (Feb 26)
      runtests: make random seed fixed for a month
      docs/RELEASE-PROCEDURE.md: pushed some release dates
      KNOWN_BUGS: AUTH PLAIN for SMTP is not working on all servers
      bump: work towards 7.69.0 is started
      tool_dirhie.c: fix the copyright year range
      curl.h: remove WIN32 define
      include: remove non-curl prefixed defines
      libtest/mk-lib1521: adapt to new public header layout
      test1167: verify global symbols in public headers are curl prefixed
      scripts/delta: adapt to new public header layout
      fix: Copyright year out of date, should be 2020
      misc: Copyright year out of date, should be 2020
      curl: remove 'config' field from OutStruct
      wolfSSH: new SSH backend
      curl: make #0 not output the full URL
      ConnectionExists: respect the max_concurrent_streams limits
      RELEASE-NOTES: synced
      HTTP-COOKIES.md: describe the cookie file format
      wolfssh: remove fprintf() calls (and uses of __func__)
      wolfssh: set the password correctly for PASSWORD auth
      curl:progressbarinit: ignore column width from terminals < 20
      polarssl: removed
      wolfssl: use the wc-prefixed symbol alternatives
      RELEASE-NOTES: synced
      ROADMAP: thread-safe `curl_global_init()`
      http.h: Copyright year out of date, should be 2020
      data.d: remove "Multiple files can also be specified"
      copyright: fix year ranges
      RELEASE-NOTES: synced
      mk-ca-bundle: add support for CKA_NSS_SERVER_DISTRUST_AFTER
      openssl: make CURLINFO_CERTINFO not truncate x509v3 fields
      wolfssh: make it init properly via Curl_ssh_init()
      singleuse.pl: support new API functions, fix curl_dbg_ handling
      strcase: turn Curl_raw_tolower into static
      conncache: removed unused Curl_conncache_bundle_size()
      llist: removed unused Curl_llist_move()
      global_init: assume the EINTR bit by default
      curl: make the -# spaceship bar not wrap the line
      RELEASE-NOTES: synced
      curl.h: define CURL_WIN32 on windows
      global_init: move the IPv6 works status bool to multi handle
      urlapi: guess scheme correct even with credentials given
      location.d: the method change is from POST to GET only
      multi_done: if multiplexed, make conn->data point to another transfer
      oauth2-bearer.d: works for HTTP too
      KNOWN_BUGS: Multiple methods in a single WWW-Authenticate: header
      cookie: check __Secure- and __Host- case sensitively
      ngtcp2: update to git master and its draft-25 support
      altsvc: use h3-25
      quiche: Copyright year out of date
      tool_operhlp: Copyright year out of date, should be 2020
      RELEASE-NOTES: synced
      docs/HTTP3: update the OpenSSL branch to use for ngtcp2
      altsvc: set h3 version at a common single spot
      RELEASE-PROCEDURE: feature win is closed post-release a few days
      docs/HTTP3: add --enable-alt-svc to curl's configure
      curl: error on --alt-svc use w/o support
      ftp: shrink temp buffers used for PORT
      scripts: use last set tag if none given
      ftp: remove superfluous checking for crlf in user or pwd
      ftp: remove the duplicated user/password struct fields
      altsvc: keep a copy of the file name to survive handle reset
      RELEASE-NOTES: synced
      CURLOPT_ALTSVC_CTRL.3: fix the DEFAULT wording
      create-dirs.d: mention the mode
      strerror.h: Copyright year out of date
      azure: disable brotli on the macos debug-builds
      TODO: CURLOPT_SSL_CTX_FUNCTION for LDAPS
      TODO: Paged searches on LDAP server
      ftp: convert 'sock_accepted' to a plain boolean
      multi: if Curl_readwrite sets 'comeback' use expire, not loop
      socks: make the connect phase non-blocking
      RELEASE-NOTES: synced
      cookies: make saving atomic with a rename
      rename: a new file for Curl_rename()
      altsvc: make saving the cache an atomic operation
      docs/GOVERNANCE: refreshed + added "donations" and "commercial support"
      CURLOPT_REDIR_PROTOCOLS.3: update the DEFAULT section
      SOCKS: fix typo in printf formatting
      nit: Copyright year out of date
      HTTP-COOKIES: mention that a trailing newline is required
      connect: remove some spurious infof() calls
      cleanup: comment typos
      gtls: fix the copyright year
      http2: now require nghttp2 >= 1.12.0
      RELEASE-NOTES: synced
      http: added 417 response treatment
      cookie: remove unnecessary check for 'out != 0'
      http2: make pausing/unpausing set/clear local stream window
      RELEASE-NOTES: synced
      Curl_is_ASCII_name: handle a NULL argument
      smtp: fix memory leak on exit path
      runtests: restore the command log
      CIfuzz: switch off 'dry_run' mode
      smtp: overwriting 'from' leaks memory
      TODO: curl --proxycommand
      pause: force-drain the transfer on unpause
      build: remove all HAVE_OPENSSL_ENGINE_H defines
      altsvc: both h3 backends now speak h3-27
      Revert "mime: fix the binary encoder to handle large data properly"
      Revert "mime: do not perform more than one read in a row"
      Revert "mime: latch last read callback status."
      formdata/mime: copyright year range update
      configure: bump the AC_COPYRIGHT year range
      tests: disable 962, 963 and 964 on Windows
      http: mark POSTs with no body as "upload done" from the start
      multi_wait: stop loop when sread() returns zero
      dist: include tests/azure.pm in the tarball
      Revert "sha256: Added SecureTransport implementation"
      THANKS: from 7.69.0
      RELEASE-NOTES: 7.69.0

Emil Engler (3):
      ngtcp2: Add an error code for QUIC connection errors
      curl: Let -D merge headers in one file again
      github: Instructions to post "uname -a" on Unix systems in issues

Faizur Rahman (1):
      schannel: Make CURLOPT_CAINFO work better on Windows 7

Frank Gevaerts (2):
      contrithanks: Use the most recent tag by default
      contributors: Also include people who contributed to curl-www

Harry Sintonen (2):
      ngtcp2: fixed to only use AF_INET6 when ENABLE_IPV6
      altsvc: improved header parser

Jay Satiro (17):
      tool_dirhie: Allow directory traversal during creation
      vtls: Refactor Curl_multissl_version to make the code clearer
      multi: Change curl_multi_wait/poll to error on negative timeout
      schannel_verify: Fix alt names manual verify for UNICODE builds
      CURLOPT_PROXY_SSL_OPTIONS.3: Sync with CURLOPT_SSL_OPTIONS.3
      README: mention that the docs is in docs/
      asyn-thread: remove dead code
      easy: remove dead code
      multi: fix outdated comment
      strerror: Increase STRERROR_LEN 128 -> 256
      tool_homedir: Change GetEnv() to use libcurl's curl_getenv()
      CURLINFO_COOKIELIST.3: Fix example
      tool_util: Improve Windows version of tvnow()
      runtests: fix output to command log
      curl_getenv.3: Fix the memory handling description
      curl_escape.3: Add a link to curl_free
      cmake: Show HTTPS-proxy in the features output

Jon Rumsey (1):
      urldata: do string enums without #ifdefs for build scripts

Jonathan Cardoso Machado (1):
      docs: fix typo on CURLINFO_RETRY_AFTER - alwaus -> always

Leo Neat (1):
      github action: add CIFuzz

Marc Aldorasi (1):
      cmake: Enable SMB for Windows builds

Marc Hoersken (15):
      tests: fix Python 3 compatibility of smbserver.py
      ci/tests: Add Windows builds via Azure Pipelines using Docker
      ci/tests: align Azure Pipeline job names with each other
      ci/tests: Increase timeouts of Windows builds due to new tests
      ci/tests: Send test results to Azure DevOps for reporting
      ci/tests: Make sure that the AZURE_ACCESS_TOKEN is available
      ci/tests: Fix typo in previous commit 597cf2
      ci/tests: Update Azure DevOps pipeline job display names
      ci/tests: fine-tune Azure Pipeline timeouts with a small puffer
      ci/tests: some MacOS builds randomly take longer than 20min
      ci/tests: Send test results to AppVeyor for status overview
      ci/tests: Move CI test result creation above environment setup
      README.md: add Azure DevOps Pipelines build status badge
      ci/tests: Make it possible to still run but ignore failing tests
      ci/tests: fix escaping of testnames and disable proxy for CI APIs

Marcel Raad (6):
      hostip: move code to resolve IP address literals to `Curl_resolv`
      CMake: use check_symbol_exists also for inet_pton
      libssh2: fix variable type
      CMake: support specifying the target Windows version
      travis: update non-OpenSSL Linux jobs to Bionic
      openssl: remove redundant assignment

Nick Zitzmann (1):
      md4: use init/update/final functions in Secure Transport

Nicolas Guillier (1):
      cmake: Improve libssh2 check on Windows

Orgad Shaneh (1):
      curl: avoid using strlen for testing if a string is empty

Patrick Monnerat (3):
      mime: latch last read callback status.
      mime: do not perform more than one read in a row
      mime: fix the binary encoder to handle large data properly

Pavel Volgarev (1):
      smtp: Allow RCPT TO command to fail for some recipients

Pedro Monreal (1):
      cleanup: fix typos and wording in docs and comments

Peter Piekarski (1):
      conn: do not reuse connection if SOCKS proxy credentials differ

Pierre-Yves Bigourdan (1):
      digest: Do not quote algorithm in HTTP authorisation

Rolf Eike Beer (1):
      CMake: clean up and improve build procedures

Santino Keupp (1):
      libssh2: add support for forcing a hostkey type

Steve Holme (50):
      ntlm: Move the winbind data into the NTLM data structure
      ntlm: Ensure the HTTP header data is not stored in the challenge/response
      ntlm: Pass the Curl_easy structure to the private winbind functions
      ntlm_wb: Use Curl_socketpair() for greater portability
      checksrc.bat: Fix not being able to run script from the main curl directory
      url: Include the failure reason when curl_win32_idn_to_ascii() fails
      smtp: Simplify the MAIL command and avoid a duplication of send strings
      tool_home: Fix the copyright year being out of date
      win32: USE_WIN32_CRYPTO to enable Win32 based MD4, MD5 and SHA256 functions
      md4: Fixed compilation issues when using GNU TLS gcrypt
      tests: Added a unit test for SHA256 digest generation
      digest: Corrected the name of the local HTTP digest function
      md5/sha256: Updated the functions to allow non-string data to be hashed
      ntlm: Removed the dependency on the TLS libaries when using MD5
      test1610: Fixed the link to the unit test
      md4: Use const for the length input parameter
      tests: Added a unit test for MD4 digest generation
      ntlm: Moved the HMAC MD5 function into the HMAC module as a generic function
      hmac: Added a unit test for the HMAC hash generation
      ftpserver: Corrected the e-mail address regex in MAIL_smtp() and RCTP_smtp()
      ftpserver: Updated VRFY_smtp() so the response isn't necessary in the test case
      smtp: Added UTF-8 mailbox tests to verify existing behaviour
      url: Make the IDN conversion functions available to others
      smtp: Support UTF-8 based host names in the MAIL command
      smtp: Support UTF-8 based host names in the RCPT TO command
      smtp: Support UTF-8 based host names in the VRFY command
      smtp: Detect server support for the UTF-8 extension as defined in RFC-6531
      smtp: Support the SMTPUTF8 extension in the MAIL command
      smtp: Support the SMTPUTF8 extension in the RCPT TO command
      smtp: Support the SMTPUTF8 extension in the VRFY command
      smtp: Support the SMTPUTF8 extension for the EXPN command
      smtp: Tidy up, following recent changes, to maintain the coding style
      test1323: Added the missing 'unit test' feature requirement in the test case
      tests: Automatically deduce the tool name from the test case for unit tests
      RELEASE-NOTES: Corrected the link to issue #4892
      gtls: Fixed compilation when using GnuTLS < 3.5.0
      md4: Use non-deprecated functions in mbedTLS >= 2.7.0
      md5: Use pointer notation for array parameters in GnuTLS implementation
      md5: Added implementation for mbedTLS
      polarssl: Additional removal
      configure.ac: Disable metalink support if an incompatible SSL/TLS specified
      unit1651: Fixed conversion compilation warning
      tests: disable SMTP UTF-8 tests on Windows
      sha256: Added GNU TLS Nettle implementation
      sha256: Added GNU TLS gcrypt implementation
      sha256: Added mbedtls implementation
      sha256: Added SecureTransport implementation
      sha256: Added WinCrypt implementation
      sha256: Tidy up following recent changes
      configure.ac: Disable metalink if mbedTLS is specified

Tobias Hieta (1):
      CMake: Add support for CMAKE_LTO option.

jethrogb (1):
      GnuTLS: Always send client cert

nao (1):
      http: move "oauth_bearer" from connectdata to Curl_easy

加藤郁之 (1):
      HTTP: increase EXPECT_100_THRESHOLD to 1Mb